language: php

before_install: ./.travis/before_install.php
install: ./.travis/install.php
script: ./.travis/script.php

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.1.*
    - php: 7.2
      env: SYMFONY_VERSION=4.2.*
